#!/bin/sh

tmp_path=/worksource/ubuntu-installer/wubi/3rd_stuff

#Required programs
python_url="http://www.python.org/ftp/python/2.7.4/python-2.7.4.msi"
python_md5="ba6f9eb9da40ad23bc631a1f31149a01"
p7zip_url="http://nchc.dl.sourceforge.net/project/sevenzip/7-Zip/9.22/7z922.exe"
p7zip_md5="d2810e3dd4b60ab05fe7c29a50921efa"
pywin_url="http://nchc.dl.sourceforge.net/project/pywin32/pywin32/Build%20218/pywin32-218.win32-py2.7.exe"
pywin_md5="eceb1b2d9a0d854cb7c7dace13680fba"

#Compiled modules
pycrypto_url="http://www.voidspace.org.uk/downloads/pycrypto26/pycrypto-2.6.win32-py2.7.exe"
pycrypto_md5="1556d8e51b18fee30f12e22abbf0e46f"

#2.3 modules (not needed in python 2.4+)
ctypes_url="http://downloads.sourceforge.net/ctypes/ctypes-1.0.2.win32-py2.3.exe"
ctypes_md5="9afe4b75240a8808a24df7a76b6081e3"
subprocess_url="http://effbot.org/media/downloads/subprocess-0.1-20041012.win32-py2.3.exe"
subprocess_md5="00a249ec321786b17b8bb87a4eebcaeb"

# Unit test stuff
mock_url="http:/https://pypi.python.org/packages/source/m/mock/mock-1.0.1.zip"
mock_md5="869f08d003c289a97c1a6610faf5e913"

root="$(cd ${0%/*}/../;pwd)"
export WINEPREFIX="$root"/wine
python_site="$WINEPREFIX/drive_c/Python27/Lib/site-packages"
toolsdir="$root/tools"

download(){
    #wget  -P /tmp -O "$2" "$1"
    #md5=$(md5sum $2)
    #md5=${md5%% *}
    #if [ ! "$md5" = "$3" ]; then
    #    echo "Invalid download for $1, md5 does not match"
    #    exit 1
    #fi
    echo "skip download"
}

install_7z(){
    echo "Installing 7z..."
    download "$p7zip_url" "${tmp_path}/p7zip.exe" "$p7zip_md5"
    wine "${tmp_path}/p7zip.exe"
}

install_wine(){
    if [ ! -x /usr/bin/wine -a ! -x /usr/local/bin/wine ]; then
        echo "Installing wine..."
        sudo apt-get install wine #TBD do not assume apt
    fi
    #echo "Creating wine folder..."
    #wineprefixcreate --prefix "$WINEPREFIX"
}

install_mingw32(){
    if [ ! -x /usr/bin/i586-mingw32msvc-gcc -a ! -x /usr/local/bin/i586-mingw32msvc-gcc ]; then
        echo "Installing mingw32..."
        sudo apt-get install mingw32 #TBD do not assume apt
    fi
}

install_unzip(){
    if [ ! -x /usr/bin/unzip -a ! -x /usr/local/bin/unzip ]; then
        echo "Installing unzip..."
        sudo apt-get install unzip #TBD do not assume apt
    fi
}

install_python(){
    echo "Installing python..."
    download "$python_url" "${tmp_path}/python.msi" "$python_md5"
    #wine msiexec /i ${tmp_path}/${python_url##*/} /qb /ADDLOCAL=DefaultFeature /ALLUSERS=1
    #wine "${tmp_path}/python.exe"
    wine msiexec /i "${tmp_path}/python.msi"
}

install_pywin(){
    echo "Installing pywin..."
    download "$pywin_url" "${tmp_path}/pywin.exe" "$pywin_md5"
    wine "${tmp_path}/pywin.exe"
}

install_ctypes(){
    echo "Installing ctypes..."
    download "$ctypes_url" "${tmp_path}/ctypes.exe" "$ctypes_md5"
    wine "${tmp_path}/ctypes.exe"
}

install_mock(){
    download "$mock_url" "${tmp_path}/mock.zip" "$mock_md5"
    unzip -jo "${tmp_path}/mock.zip" `zipinfo -1 "${tmp_path}/mock.zip" |sed -n '/\bmock.py$/p'` -d "/tmp"
    cp "/tmp/mock.py" "$python_site"
}

install_subprocess(){
    echo "Installing subprocess..."
    download "$subprocess_url" "${tmp_path}/subprocess.exe" "$subprocess_md5"
    wine "${tmp_path}/subprocess.exe"
}

install_pycrypto(){
    echo "Installing pycrypto..."
    #download "$pycrypto_url" "${tmp_path}/pycrypto.zip" "$pycrypto_md5"
    #install_unzip
    #unzip "${tmp_path}/pycrypto.zip" -d "/tmp"
    #cp -a "${tmp_path}/Crypto" "$python_site"
    download "$pycrypto_url" "${tmp_path}/pycrypto.exe" "$pycrypto_md5"
    wine "${tmp_path}/pycrypto.exe"
}

make_wine(){
    install_wine
    install_mingw32
    install_7z
    install_python
    #~ install_pywin
    #~ install_ctypes
    #~ install_subprocess
    install_pycrypto
    install_mock
}

if [ ! -e "$root/wine" ]; then
    make_wine
fi
